dist: jessie
language: node_js

sudo: false

node_js:
  - 4
  - 6
  - 8

before_script:
  - npm install -g yarn
  - npm install -g ts-node
  - npm install tslint
  - npm install typescript

script:
  - yarn
  - yarn lint
  - yarn test
  - yarn build